[package]
name = "filler"
version = "0.1.0"
edition = "2021"

# Define the library part
[lib]
name = "filler_lib"
path = "solution/src/lib.rs"

# Define the binary part
[[bin]]
name = "filler"
path = "solution/src/main.rs"

[dependencies]
